# yoinked from Marlon
name: NuGet Push
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: GIT Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build & Pack NuGet Package(s)
        run: dotnet pack -c Release -o "./nuget-packages"

      - name: Upload Build Artifact(s)
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: ./nuget-packages
      
      - name: Add nuget source
        working-directory: ./nuget-packages
        run: dotnet nuget add source --name "GitHub" --username "tuankien2601" --password ${{ secrets.PASSWORD }} --store-password-in-clear-text "https://nuget.pkg.github.com/tuankien2601/index.json"

      - name: Push NuGet Package(s)
        working-directory: ./nuget-packages
        run: dotnet nuget push "*.nupkg" --source GitHub --skip-duplicate --api-key ${{ secrets.PASSWORD }}
